# Generated by Django 4.1.6 on 2024-04-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0032_gramsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minmaxsetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minvalue', models.IntegerField(blank=True, null=True)),
                ('maxvalue', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_max_setup', to='setup.product')),
            ],
        ),
    ]
