# Generated by Django 4.1.6 on 2024-05-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0033_minmaxsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartonSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton', models.IntegerField()),
                ('current_carton', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_setups', to='setup.product')),
            ],
        ),
    ]
